#!/bin/bash

GOOS=windows GOARCH=amd64 go build --ldflags="-H windowsgui" ./cmd/switch
GOOS=windows GOARCH=amd64 go build --ldflags="-H windowsgui" ./cmd/dimmer
GOOS=windows GOARCH=amd64 go build --ldflags="-H windowsgui" ./cmd/brighter
