#!/bin/bash

GOOS=windows GOARCH=amd64 go build -o release/win-amd64/switch.exe --ldflags="-H windowsgui" ./cmd/switch
GOOS=windows GOARCH=amd64 go build -o release/win-amd64/dimmer.exe --ldflags="-H windowsgui" ./cmd/dimmer
GOOS=windows GOARCH=amd64 go build -o release/win-amd64/brighter.exe --ldflags="-H windowsgui" ./cmd/brighter
